### ISSUE TITLE
story link is expired

### ISSUE THREAD

**Issue by Globebyte** [gocardless/react-dropin#9]
The link to view the story to demonstrate this "dropin" simply says the link is expired, so its not possible to see it in action.  thanks

**Comment by markwilson** [comment]
Thanks for raising this!

For clarity, the expired link is to one of our payment flows. The reason it shows as expired is because the Storybook sets the drop-in to use a fake Billing Request Flow ID (`BRF123`).

This was originally by design because the intention of this Storybook was to show the button itself (and the styles of the modal) rather than show the full payment flow. But you're right; it's not showing useful context.

While we figure out a more sensible approach than linking to a dummy payment flow that doesn't exist, there's a couple of other things you can try if this is blocking you from progressing with the drop-in solution.

Firstly, if you're looking to see what the payment flow steps look like, the best place to look is our [Anatomy of a Billing Request Flow document](https://developer.gocardless.com/getting-started/billing-requests/anatomy-of-a-billing-request-flow/).

Secondly, if you're specifically wanting to see the modal with a payment flow inside, here's a workaround for making the Storybook work:-
1. Open the [sandbox demo payment URL](https://pay-sandbox.gocardless.com/billing_request_flows/demo)
2. Wait for it to redirect you to a payment flow
3. Copy the Billing Request Flow ID from the URL (it starts with `BRF`)
4. Open the Storybook
5. Click into the Controls tab
6. Paste the Billing Request Flow ID into the relevant control field
7. Try the button in the canvas and see the modal showing a payment flow

**Comment by MinasG** [comment]
Hey @markwilson, thank you for providing the above info to solve the "expired" story. 

It would probably help everyone coming across the repo to see the above workaround in the readme as this issue might be easy to miss. Alternatively (or additionally), adding it to the story docs would also improve the UX.

I am happy to raise a PR if you want me to 😃.

**Comment by markwilson** [comment]
Thanks for the suggestion, @MinasG! I've updated the storybook now to include the instructions above.

**Comment by MinasG** [comment]
@markwilson perfect, thank you for sorting that out.
